(() => {
  if (window.__mc1stRulesChatbot) return;
  window.__mc1stRulesChatbot = true;
  const endpoint = 'https://ai.mc-1st.ro/chat';
  const quickQuestions = ['Ce sancțiune are spamul pe chat?', 'Este permis X-Ray?', 'Ce se întâmplă dacă insult pe chat?'];
  const style = document.createElement('style');
  style.textContent = `
    :root { --mc-blue:#346ddb; --mc-panel:#11182a; --mc-soft:#17213a; --mc-border:rgba(148,163,184,.24); }
    #mc1st-rules-trigger {position:fixed;right:24px;bottom:24px;z-index:99999;display:inline-flex;align-items:center;gap:10px;border:1px solid rgba(147,197,253,.5);border-radius:14px;padding:12px 15px;color:#f8fafc;background:linear-gradient(135deg,#1d4ed8,var(--mc-blue));box-shadow:0 14px 35px #0006;font:700 13px/1 "JetBrains Mono",ui-monospace,monospace;cursor:pointer;transition:.18s} #mc1st-rules-trigger:hover{transform:translateY(-2px);box-shadow:0 18px 42px #0008} #mc1st-rules-trigger svg{width:19px;height:19px}
    #mc1st-rules-panel{position:fixed;right:24px;bottom:84px;z-index:99999;width:min(416px,calc(100vw - 28px));overflow:hidden;border:1px solid var(--mc-border);border-radius:18px;color:#e5edf9;background:var(--mc-panel);box-shadow:0 24px 70px #0009;font:14px/1.55 "JetBrains Mono",ui-monospace,monospace;opacity:0;transform:translateY(10px) scale(.98);pointer-events:none;transition:.18s}#mc1st-rules-panel.open{opacity:1;transform:none;pointer-events:auto}
    .mc-top{display:flex;align-items:center;justify-content:space-between;padding:15px 16px;border-bottom:1px solid var(--mc-border);background:radial-gradient(circle at top left,rgba(52,109,219,.35),transparent 48%),#121b30}.mc-title{display:flex;align-items:center;gap:10px;font-size:13px;font-weight:800}.mc-title i{display:grid;width:28px;height:28px;place-items:center;border-radius:9px;color:#dbeafe;background:var(--mc-blue);font-style:normal}.mc-close{width:30px;height:30px;border:0;border-radius:8px;color:#b9c6dc;background:transparent;font:25px/1 system-ui;cursor:pointer}.mc-close:hover{color:white;background:#ffffff14}
    #mc1st-rules-messages{display:flex;height:min(390px,46vh);flex-direction:column;gap:10px;overflow-y:auto;padding:15px;scrollbar-width:thin}.mc-msg{max-width:94%;padding:10px 12px;border:1px solid var(--mc-border);border-radius:12px;white-space:pre-wrap;word-break:break-word}.mc-bot{align-self:flex-start;background:var(--mc-soft)}.mc-user{align-self:flex-end;border-color:#93c5fd4d;color:#fff;background:#244d9d}.mc-error{border-color:#f871716b;color:#fecaca;background:#7f1d1d47}.mc-label{display:block;margin:0 0 5px;color:#75a7ff;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.mc-sanction{display:block;margin-top:9px;padding-top:8px;border-top:1px solid var(--mc-border);color:#fde68a}.mc-sources{margin-top:9px;font-size:11px}.mc-sources a{color:#93c5fd;text-decoration:none}.mc-sources a:hover{text-decoration:underline}
    #mc1st-rules-quick{display:flex;flex-wrap:wrap;gap:7px;padding:0 15px 12px}.mc-quick{border:1px solid var(--mc-border);border-radius:999px;padding:6px 9px;color:#c8d6ed;background:transparent;font:10px/1.25 "JetBrains Mono",ui-monospace,monospace;cursor:pointer;text-align:left}.mc-quick:hover{border-color:#5c8ded;color:white;background:#346ddb29}
    #mc1st-rules-form{display:flex;align-items:flex-end;gap:9px;padding:12px;border-top:1px solid var(--mc-border);background:#0d1424}#mc1st-rules-input{min-height:42px;max-height:110px;flex:1;resize:none;border:1px solid var(--mc-border);border-radius:10px;padding:11px 12px;outline:none;color:#f8fafc;background:var(--mc-soft);font:12px/1.4 "JetBrains Mono",ui-monospace,monospace}#mc1st-rules-input:focus{border-color:#5c8ded;box-shadow:0 0 0 3px #346ddb29}#mc1st-rules-send{height:42px;border:0;border-radius:10px;padding:0 13px;color:white;background:var(--mc-blue);font:800 11px/1 "JetBrains Mono",ui-monospace,monospace;cursor:pointer}#mc1st-rules-send:disabled{cursor:wait;opacity:.6}@media(max-width:540px){#mc1st-rules-trigger{right:14px;bottom:14px}#mc1st-rules-panel{right:14px;bottom:72px}#mc1st-rules-messages{height:44vh}}
  `;
  document.head.append(style);
  const trigger = document.createElement('button');
  trigger.id = 'mc1st-rules-trigger'; trigger.type = 'button';
  trigger.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/><path d="M8 11h8M8 15h5"/></svg> Întreabă regulamentul';
  const panel = document.createElement('section');
  panel.id = 'mc1st-rules-panel'; panel.setAttribute('aria-label', 'Asistent regulament MC-1ST');
  panel.innerHTML = '<div class="mc-top"><div class="mc-title"><i>?</i><span>ASISTENT REGULAMENT</span></div><button class="mc-close" type="button" aria-label="Închide asistentul">×</button></div><div id="mc1st-rules-messages"></div><div id="mc1st-rules-quick"></div><form id="mc1st-rules-form" novalidate><textarea id="mc1st-rules-input" maxlength="1000" rows="1" placeholder="Scrie întrebarea ta despre reguli…" aria-label="Întrebarea ta"></textarea><button id="mc1st-rules-send" type="submit">TRIMITE</button></form>';
  document.body.append(trigger, panel);
  const messages = panel.querySelector('#mc1st-rules-messages'), quick = panel.querySelector('#mc1st-rules-quick'), input = panel.querySelector('#mc1st-rules-input'), form = panel.querySelector('form'), send = panel.querySelector('#mc1st-rules-send');
  function addMessage(text, type = 'bot', sources = [], sanction = '') { const item = document.createElement('article'); item.className = `mc-msg mc-${type}`; if (type !== 'user') { const label = document.createElement('span'); label.className = 'mc-label'; label.textContent = type === 'error' ? 'Eroare' : 'Regulament MC-1ST'; item.append(label); } const content = document.createElement('span'); content.textContent = text; item.append(content); if (sanction) { const value = document.createElement('strong'); value.className = 'mc-sanction'; value.textContent = `Sancțiune: ${sanction}`; item.append(value); } if (sources.length) { const links = document.createElement('div'); links.className = 'mc-sources'; links.append('Sursă: '); sources.forEach((source, index) => { const link = document.createElement('a'); link.href = source.url; link.target = '_blank'; link.rel = 'noopener'; link.textContent = source.title; links.append(link); if (index < sources.length - 1) links.append(', '); }); item.append(links); } messages.append(item); messages.scrollTop = messages.scrollHeight; return item; }
  async function submit(question) { question = question.trim(); if (question.length < 3) { addMessage('Scrie o întrebare de cel puțin 3 caractere.', 'error'); input.focus(); return; } addMessage(question, 'user'); input.value = ''; send.disabled = true; const pending = addMessage('Caut regula și sancțiunea aplicabilă…'); try { const response = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ question }) }); const result = await response.json(); pending.remove(); if (!response.ok) throw new Error(result.error || 'Nu am putut răspunde acum.'); addMessage(result.answer, 'bot', result.sources || [], result.sanction || 'Regulamentul nu precizează o sancțiune exactă.'); } catch (error) { pending.remove(); addMessage(error.message || 'Nu am putut răspunde acum. Încearcă din nou.', 'error'); } finally { send.disabled = false; input.focus(); } }
  addMessage('Îți răspund doar din regulamentul oficial și îți arăt sursa exactă.'); quickQuestions.forEach(question => { const button = document.createElement('button'); button.className = 'mc-quick'; button.type = 'button'; button.textContent = question; button.onclick = () => submit(question); quick.append(button); }); trigger.onclick = () => { panel.classList.toggle('open'); if (panel.classList.contains('open')) input.focus(); }; panel.querySelector('.mc-close').onclick = () => panel.classList.remove('open'); form.onsubmit = event => { event.preventDefault(); submit(input.value); }; input.oninput = () => { input.style.height = 'auto'; input.style.height = `${Math.min(input.scrollHeight, 110)}px`; };
})();
